Updat. Go.build.pages.yml
[![Go-publisher] https://github.com/QUBUHUB/go-libs/actions/workflows/Go.build.pages.yml/badge.svg)](https://github.com/QUBUHUB/go-libs/actions/workflows/Go.build.pages.yml)

- name: Upload a Build Artifact
  uses: actions/upload-artifact@v3.1.3
  with:
    # Artifact name
    name: # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: 
    # The desired behavior if no files are found using the provided path.
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: # optional, default is warn
https://github.blog/changelog/2023-06-   13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

    # Duration after which artifact will expire in days. 0 means using default retention.
Minimum 1 day. Maximum 90 days unless changed from the repository settings page.h

https://github.com/trustwallet/go-libs/commits?
# Author
QUBUHUB